import React from "react";
import { PlaceholderIcon } from "./_placeholderIcon";
import type { IconProps } from "./IconProps";

const AutoGeneratedIcon: React.FC<IconProps> = (props) => (
  <PlaceholderIcon name="AutoGeneratedIcon" {...props} />
);
export default AutoGeneratedIcon;
