import SaveIcon from "./SaveIcon";
import SendIcon from "./SendIcon";
import CloseIcon from "./CloseIcon.jsx";
import EditIcon from "./EditIcon.js";
import AutoGeneratedIcon from "./AutoGeneratedIcon";
import DownArrow from "./DownArrow.jsx";
import UpArrow from "./UpArrow.jsx";
import CommentIcon from "./CommentIcon.jsx";
import NoCommentsIcon from "./NoCommentIcon.jsx";
import LeftArrowIcon from "./LeftArrowIcon.jsx";
import RightArrowIcon from "./RightArrowIcon.jsx";
import HamBurgerIcon from "./HamBurgerIcon.jsx";
import LogoIcon from "./LogoIcon.jsx";
import SearchIcon from "./SearchIcon.jsx";
import ExpandComparisonIcon from "./ExpandComparisonIcon.jsx";
import SignOut from "./SignOut.jsx";
import ResetIcon from "./ResetIcon.js";
import InfoIcon from "./InfoIcon.jsx";
import DragIcon from "./DragIcon.jsx";
import WarningIcon from "./WarningIcon.jsx";
import IdeaIcon from "./IdeaIcon.jsx";
import DownloadIcon from "./DownloadIcon.jsx";
import InsightIcon from "./InsightIcon.jsx";
import AiMagicIcon from "./AIMagicIcon.jsx";
import CopyIcon from "./CopyIcon.jsx";
import LikeIcon from "./LikeIcon.jsx";
import CheckIcon from "./CheckIcon.jsx";
import DictionaryCrossIcon from "./DictionaryCrossIcon.jsx";
import DictionaryIcon from "./DictionaryIcon.jsx";
import MarketShareIcon from "./MarketShareIcon.jsx";
import MarketValuationIcon from "./MarketValuationIcon.jsx";
import MbpScoreIcon from "./MbpScoreIcon.jsx";
import NexScoreIcon from "./NexScoreIcon.jsx";
import OnAirSitesIcon from "./OnAirSitesIcon.jsx";
import StarIcon from "./StarIcon.jsx";
import SortIcon from "./SortIcon.jsx";
import RejectSnackbarIcon from "./RejectSnackbarIcon.jsx";
import ApproveSnackbarIcon from "./ApprovSnackbarIcon.jsx";
import SnackbarCrossIcon from "./SnackbarCrossIcon.jsx";
import KebabMenuIcon from "./KababMenuIcon.jsx";
import PurpleHex from "./PurpleHex.jsx";
import BlueHex from "./BlueHex.jsx";
import OrangeHex from "./OrangeHex.jsx";
import GreyHex from "./GreyHex.jsx";
import AiMagicIcon2 from "./AIMagicIcon2.jsx";
import UnknownPersonIcon from "./UnknownPersonIcon.jsx";
import BugIcon from "./BugIcon.jsx";
import QGPReportIcon from "./QGPReportIcon.jsx";
import AIMagicIcon3 from "./AIMagicIcon3.jsx";
import Warning2 from "./Warning2.jsx";
import StatusIcon from "./StatusIcon.jsx";
import CsvFileIcon from "./CSVFileIcon.jsx";
import ExpandIcon from "./ExpandedIcon.jsx";
import Dustbinicon from "./Dustbinicon.jsx";
import Editpen from "./Editpen.jsx";
import Markapproved from "./Markapproved.jsx";
import GisIcon from "./GisIcon.jsx";
import ExpansionIcon from "./ExpantionIcon.jsx";
import ClusterIcon from "./ClusterIcon.jsx";
import ExecutiveSkeletonIcon from "./ExecutiveIcon.jsx";
import ClockIcon from "./Clock.jsx";
import NewCrossIcon from "./NewCrossIcon.jsx"
import AIChatIcon from "./AIChatIcon.jsx";

export {
  SaveIcon,
  SendIcon,
  CloseIcon,
  EditIcon,
  AutoGeneratedIcon,
  DownArrow,
  UpArrow,
  CommentIcon,
  NoCommentsIcon,
  LeftArrowIcon,
  RightArrowIcon,
  LogoIcon,
  HamBurgerIcon,
  SearchIcon,
  ExpandComparisonIcon,
  SignOut,
  ResetIcon,
  InfoIcon,
  DragIcon,
  WarningIcon,
  IdeaIcon,
  DownloadIcon,
  InsightIcon,
  AiMagicIcon,
  CopyIcon,
  LikeIcon,
  CheckIcon,
  DictionaryCrossIcon,
  DictionaryIcon,
  MarketShareIcon,
  MarketValuationIcon,
  MbpScoreIcon,
  ClockIcon,
  NexScoreIcon,
  OnAirSitesIcon,
  StarIcon,
  SortIcon,
  RejectSnackbarIcon,
  ApproveSnackbarIcon,
  SnackbarCrossIcon,
  KebabMenuIcon,
  PurpleHex,
  OrangeHex,
  BlueHex,
  GreyHex,
  AiMagicIcon2,
  UnknownPersonIcon,
  BugIcon,
  QGPReportIcon,
  AIMagicIcon3,
  Warning2,
  StatusIcon,
  CsvFileIcon,
  ExpandIcon,
  Dustbinicon,
  Editpen,
  Markapproved,
  GisIcon,
  ExpansionIcon,
  ClusterIcon,
  ExecutiveSkeletonIcon,
  NewCrossIcon,
  AIChatIcon,
};
